# Generated by Django 5.2.1 on 2025-06-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField()),
                ('introduction', models.CharField(verbose_name=models.TextField())),
                ('content', models.CharField(verbose_name=models.TextField())),
                ('conclusion', models.CharField(verbose_name=models.TextField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('instagram_id', models.CharField()),
                ('bio', models.CharField(verbose_name=models.TextField())),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
