# Generated by Django 5.2.1 on 2025-06-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_date_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/'),
        ),
    ]
